function plan = buildfile

import matlab.buildtool.Task
import matlab.buildtool.tasks.CodeIssuesTask
import matlab.buildtool.tasks.TestTask
import matlab.unittest.Verbosity

% Create a plan with no tasks
plan = buildplan;

plan("check") = CodeIssuesTask(...
    Results='results.sarif');

plan("updateSGdeps") = Task( ...
    Description = "Update Speedgoat toolbox dependencies", ...
    Actions = @(~) updateSGdeps,...
    Outputs = "toolbox/dependencies/sg/**");

plan("test") = TestTask( ...
    Description = "Run unit tests", ...
    Dependencies = "updateSGdeps",...
    TestResults = "results.xml",...
    OutputDetail = Verbosity.Detailed,...
    Strict = true);

plan("buildDoc") = Task( ...
    Description = "Build HTML doc from sources", ...
    Actions = @(~) buildDoc,...
    Inputs = 'docSource/**/*.mlx',...
    Outputs = "toolbox/html/**/*.html");

plan("package") = Task( ...
    Description = "Package toolbox", ...
    Dependencies = ["check" "updateSGdeps" "test" "buildDoc"], ...
    Actions = @(~,toolboxVer,authorName) releaseTask(toolboxVer,authorName));

% Set default tasks in the plan
plan.DefaultTasks = ["check" "test"];

end