function plan = buildfile

import matlab.buildtool.Task

% Create a plan with no tasks
plan = buildplan;

% Call project object
projObj = currentProject;

% Create the "check" task and add it to the plan
plan("check") = Task( ...
    Description = "Identify code issues", ...
    Actions = @(~) checkTask,...
    Inputs = fullfile(projObj.RootFolder,'**/*.m'));

% Create the "test" task and add it to the plan
plan("test") = Task( ...
    Description = "Run unit tests", ...
    Actions = @(~,tags) testTask(tags),...
    Inputs = fullfile(projObj.RootFolder,'**/*.m'));

plan("buildDoc") = Task( ...
    Description = "Build HTML doc from sources", ...
    Actions = @(~) buildDoc,...
    Inputs = fullfile(projObj.RootFolder,'docSource/**/*.mlx'),...
    Outputs = fullfile(projObj.RootFolder,"toolbox/html/**/*.html"));

% Make the "release" task dependent on the "check" and "test" tasks
plan("package") = Task( ...
    Description = "Package toolbox", ...
    Dependencies = ["check" "test"], ...
    Actions = @(~,toolboxVer,authorName) releaseTask(toolboxVer,authorName),...
    Inputs = plan("buildDoc").Outputs);

% Set default tasks in the plan
plan.DefaultTasks = ["check" "test"];

end